// src/constants/adminConstants.js

export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST';
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const ALL_USERS_REQUEST = 'ALL_USERS_REQUEST';
export const ALL_USERS_SUCCESS = 'ALL_USERS_SUCCESS';
export const ALL_USERS_FAIL = 'ALL_USERS_FAIL';

export const ALL_CHATS_REQUEST = 'ALL_CHATS_REQUEST';
export const ALL_CHATS_SUCCESS = 'ALL_CHATS_SUCCESS';
export const ALL_CHATS_FAIL = 'ALL_CHATS_FAIL';

export const ALL_POSTS_REQUEST = 'ALL_POSTS_REQUEST';
export const ALL_POSTS_SUCCESS = 'ALL_POSTS_SUCCESS';
export const ALL_POSTS_FAIL = 'ALL_POSTS_FAIL';

export const ALL_MESSAGES_REQUEST = 'ALL_MESSAGES_REQUEST';
export const ALL_MESSAGES_SUCCESS = 'ALL_MESSAGES_SUCCESS';
export const ALL_MESSAGES_FAIL = 'ALL_MESSAGES_FAIL';
