export const FETCH_CHATS_REQUEST = 'FETCH_CHATS_REQUEST';
export const FETCH_CHATS_SUCCESS = 'FETCH_CHATS_SUCCESS';
export const FETCH_CHATS_FAILURE = 'FETCH_CHATS_FAILURE';

export const SEND_FRIEND_REQUEST_REQUEST = 'SEND_FRIEND_REQUEST_REQUEST';
export const SEND_FRIEND_REQUEST_SUCCESS = 'SEND_FRIEND_REQUEST_SUCCESS';
export const SEND_FRIEND_REQUEST_FAILURE = 'SEND_FRIEND_REQUEST_FAILURE';


export const ACCEPT_FRIEND_REQUEST_REQUEST = 'ACCEPT_FRIEND_REQUEST_REQUEST';
export const ACCEPT_FRIEND_REQUEST_SUCCESS = 'ACCEPT_FRIEND_REQUEST_SUCCESS';
export const ACCEPT_FRIEND_REQUEST_FAILURE = 'ACCEPT_FRIEND_REQUEST_FAILURE';


export const FETCH_NOTIFICATIONS_REQUEST = 'FETCH_NOTIFICATIONS_REQUEST';
export const FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS';
export const FETCH_NOTIFICATIONS_FAILURE = 'FETCH_NOTIFICATIONS_FAILURE';



export const FETCH_CHAT_DETAILS_REQUEST = 'FETCH_CHAT_DETAILS_REQUEST';
export const FETCH_CHAT_DETAILS_SUCCESS = 'FETCH_CHAT_DETAILS_SUCCESS';
export const FETCH_CHAT_DETAILS_FAILURE = 'FETCH_CHAT_DETAILS_FAILURE';

export const FETCH_MESSAGES_REQUEST = 'FETCH_MESSAGES_REQUEST';
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';
export const FETCH_MESSAGES_FAILURE = 'FETCH_MESSAGES_FAILURE';


export const SEND_ATTACHMENT_REQUEST = "SEND_ATTACHMENT_REQUEST";
export const SEND_ATTACHMENT_SUCCESS = "SEND_ATTACHMENT_SUCCESS";
export const SEND_ATTACHMENT_FAILURE = "SEND_ATTACHMENT_FAILURE";

export const NEW_MESSAGE_ALERT = 'NEW_MESSAGE_ALERT';
export const RESET_MESSAGE_ALERT = 'RESET_MESSAGE_ALERT';

export const REMOVE_ALERT_MESSAGE = 'REMOVE_ALERT_MESSAGE';

export const FETCH_MY_GROUPS_REQUEST = 'FETCH_MY_GROUPS_REQUEST';
export const FETCH_MY_GROUPS_SUCCESS = 'FETCH_MY_GROUPS_SUCCESS';
export const FETCH_MY_GROUPS_FAILURE = 'FETCH_MY_GROUPS_FAILURE';





export const CLEAR_ERRORS = "CLEAR_ERRORS";