export const LIKE_REPLY_REQUEST = 'LIKE_REPLY_REQUEST';
export const LIKE_REPLY_SUCCESS = 'LIKE_REPLY_SUCCESS';
export const LIKE_REPLY_FAILURE = 'LIKE_REPLY_FAILURE';

export const DISLIKE_REPLY_REQUEST = 'DISLIKE_REPLY_REQUEST';
export const DISLIKE_REPLY_SUCCESS = 'DISLIKE_REPLY_SUCCESS';
export const DISLIKE_REPLY_FAILURE = 'DISLIKE_REPLY_FAILURE';


export const LIKE_COMMENT_REQUEST = 'LIKE_COMMENT_REQUEST';
export const LIKE_COMMENT_SUCCESS = 'LIKE_COMMENT_SUCCESS';
export const LIKE_COMMENT_FAILURE = 'LIKE_COMMENT_FAILURE';

export const DISLIKE_COMMENT_REQUEST = 'DISLIKE_COMMENT_REQUEST';
export const DISLIKE_COMMENT_SUCCESS = 'DISLIKE_COMMENT_SUCCESS';
export const DISLIKE_COMMENT_FAILURE = 'DISLIKE_COMMENT_FAILURE';
