export const ALL_POST_REQUEST = "ALL_POST_REQUEST";
export const ALL_POST_SUCCESS = "ALL_POST_SUCCESS";
export const ALL_POST_FAIL = "ALL_POST_FAIL";

export const ADMIN_POST_REQUEST = "ADMIN_POST_REQUEST";
export const ADMIN_POST_SUCCESS = "ADMIN_POST_SUCCESS";
export const ADMIN_POST_FAIL = "ADMIN_POST_FAIL";

export const NEW_POST_REQUEST = "NEW_POST_REQUEST";
export const NEW_POST_SUCCESS = "NEW_POST_SUCCESS";
export const NEW_POST_RESET = "NEW_POST_RESET";
export const NEW_POST_FAIL = "NEW_POST_FAIL";

export const UPDATE_POST_REQUEST = "UPDATE_POST_REQUEST";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const UPDATE_POST_RESET = "UPDATE_POST_RESET";
export const UPDATE_POST_FAIL = "UPDATE_POST_FAIL";

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_RESET = "DELETE_POST_RESET";
export const DELETE_POST_FAIL = "DELETE_POST_FAIL";

export const POST_DETAILS_REQUEST = "POST_DETAILS_REQUEST";
export const POST_DETAILS_SUCCESS = "POST_DETAILS_SUCCESS";
export const POST_DETAILS_FAIL = "POST_DETAILS_FAIL";

export const NEW_COMMENT_REQUEST = "NEW_COMMENT_REQUEST";
export const NEW_COMMENT_SUCCESS = "NEW_COMMENT_SUCCESS";
export const NEW_COMMENT_RESET = "NEW_COMMENT_RESET";
export const NEW_COMMENT_FAIL = "NEW_COMMENT_FAIL";

export const ALL_COMMENT_REQUEST = "ALL_COMMENT_REQUEST";
export const ALL_COMMENT_SUCCESS = "ALL_COMMENT_SUCCESS";
export const ALL_COMMENT_FAIL = "ALL_COMMENT_FAIL";


export const GET_COMMENTS_REQUEST = "GET_COMMENTS_REQUEST";
export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS";
export const GET_COMMENTS_FAILURE = "GET_COMMENTS_FAILURE";


export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_RESET = "DELETE_COMMENT_RESET";
export const DELETE_COMMENT_FAIL = "DELETE_COMMENT_FAIL";

export const LIKE_POST_REQUEST ="LIKE_POST_REQUEST";
export const  LIKE_POST_SUCCESS="LIKE_POST_SUCCESS";
export const LIKE_POST_FAIL="LIKE_POST_FAIL";

export const UNLIK_POST_REQUEST="UNLIK_POST_REQUEST";
export const  UNLIK_POST_SUCCESS="UNLIK_POST_SUCCESS";
export const UNLIK_POST_FAIL="UNLIK_POST_FAIL";

export const NOT_INTERESTED_SUCCESS="NOT_INTERESTED_SUCCESS";
export const NOT_INTERESTED_FAIL="NOT_INTERESTED_FAIL";

export const ADD_REPLY_REQUEST = 'ADD_REPLY_REQUEST';
export const ADD_REPLY_SUCCESS = 'ADD_REPLY_SUCCESS';
export const ADD_REPLY_FAIL = 'ADD_REPLY_FAIL';

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const REFRESH_PAGE = 'REFRESH_PAGE';
