export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";


export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";
export const UPDATE_USER_RESET = "UPDATE_USER_RESET";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";
export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET";

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';


export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const DELETE_USER_RESET = "DELETE_USER_RESET";

export const ALL_USERS_REQUEST = "ALL_USERS_REQUEST";
export const ALL_USERS_SUCCESS = "ALL_USERS_SUCCESS";
export const ALL_USERS_FAIL = "ALL_USERS_FAIL";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

export const SEARCH_USER_REQUEST="SEARCH_USER_REQUEST";
export const SEARCH_USER_SUCCESS="SEARCH_USER_SUCCESS";
export const SEARCH_USER_FAIL ="SEARCH_USER_SUCCESS";

export const FOLLOWING_REQUEST="FOLLOWING_REQUEST";
export const FOLLOWING_SUCCESS="FOLLOWING_SUCCESS";
export const FOLLOWING_FAIL ="FOLLOWING_SUCCESS";


export const FOLLOW_USER_REQUEST = 'FOLLOW_USER_REQUEST';
export const FOLLOW_USER_SUCCESS = 'FOLLOW_USER_SUCCESS';
export const FOLLOW_USER_FAIL = 'FOLLOW_USER_FAIL';


export const UNFOLLOW_USER_REQUEST = 'UNFOLLOW_USER_REQUEST';
export const UNFOLLOW_USER_SUCCESS = 'UNFOLLOW_USER_SUCCESS';
export const UNFOLLOW_USER_FAIL = 'UNFOLLOW_USER_FAIL';

export const ALL_FOLLOW_USERS_REQUEST = 'ALL_FOLLOW_USERS_REQUEST';
export const ALL_FOLLOW_USERS_SUCCESS = 'ALL_FOLLOW_USERS_SUCCESS';
export const ALL_FOLLOW_USERS_FAIL = 'ALL_FOLLOW_USERS_FAIL';

export const ALL_FOLLOWING_USERS_REQUEST = 'ALL_FOLLOWING_USERS_REQUEST';
export const ALL_FOLLOWING_USERS_SUCCESS = 'ALL_FOLLOWING_USERS_SUCCESS';
export const ALL_FOLLOWING_USERS_FAIL = 'ALL_FOLLOWING_USERS_FAIL';

export const USER_SEARCH_REQUEST = "USER_SEARCH_REQUEST";
export const USER_SEARCH_SUCCESS = "USER_SEARCH_SUCCESS";
export const USER_SEARCH_FAILURE = "USER_SEARCH_FAILURE";



export const FOLLOWING_UPDATE = 'FOLLOWING_UPDATE';
export const FOLLOWING_UPDATE_SUCCESS = 'FOLLOWING_UPDATE_SUCCESS';
export const FOLLOWING_UPDATE_FAIL = 'FOLLOWING_UPDATE_FAIL';

export const BOOKMARK_POST_REQUEST = 'BOOKMARK_POST_REQUEST';
export const BOOKMARK_POST_SUCCESS = 'BOOKMARK_POST_SUCCESS';
export const BOOKMARK_POST_FAIL = 'BOOKMARK_POST_FAIL';
export const BOOKMARK_POST_RESET = 'BOOKMARK_POST_RESET';


export const FETCH_MY_FRIENDS_REQUEST = 'FETCH_MY_FRIENDS_REQUEST';
export const FETCH_MY_FRIENDS_SUCCESS = 'FETCH_MY_FRIENDS_SUCCESS';
export const FETCH_MY_FRIENDS_FAILURE = 'FETCH_MY_FRIENDS_FAILURE';


export const CLEAR_ERRORS = 'CLEAR_ERRORS';

